### ISSUE TITLE
Permissions not working correctly

### ISSUE THREAD

**Issue by r0w** [K3V1N32/ButtonsPlus#2]
buttonsplus.text: true
buttonsplus.charge: true

These settings don't allow a user to push a button with charge+text. as supposed http://dev.bukkit.org/server-mods/buttonsplus/pages/permissions/

I need to put :

buttonsplus.text.push: true
buttonsplus.charge.push: true

I'm also having this error when trying to answer "Yes" or "No" if I want to charge the button : 

```
21:41:20 [SEVERE] Could not pass event PlayerChatEvent to ButtonsPlus
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:786)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:103)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:169)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:571)
        at java.util.ArrayList.get(ArrayList.java:349)
        at com.K3V1N32.ButtonsPlus.ButtonCreationHandler.getFormatList(ButtonCreationHandler.java:27)
        at com.K3V1N32.ButtonsPlus.ButtonCreationHandler.getPlayerActions(ButtonCreationHandler.java:65)
        at com.K3V1N32.ButtonsPlus.ButtonCreationHandler.handleChat(ButtonCreationHandler.java:150)
        at com.K3V1N32.ButtonsPlus.ButtonPListener.onPlayerChat(ButtonPListener.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
        ... 13 more
```

But everything is fine when using OP accounts.

I'm using PermissionsBukkit, tell me if you need more info

Keep going :) great work

**Comment by K3V1N32** [comment]
All fixed, in 1.2 :D
